global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'sahil@catalysts.org'
  smtp_auth_username: 'sahil@catalysts.org'
  smtp_auth_password: 'rvll fzpn kxdg gtbz'
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'sahil@catalysts.org'
        send_resolved: true
