global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<enter your email>'
  smtp_auth_username: '<enter your email>'
  smtp_auth_password: '<enter your passowrd>'  #https://myaccount.google.com/apppasswords
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: '<enter your email>'
        send_resolved: true
